---
title: "Causal Inference for Peacekeeping Research: A Synthetic Control Approach"
abstract: "\\dropcap{M}uch of the peacebuilding literture focuses on causal relationships but neglects causal methods. In many instances, talk of 'correlation' and 'association' is insufficient with the avaliability of contemporary causal inference methods. This study furthers the study of peacebuilding by analyzing the impact of a U.N. peacekeeping operation (PKO) in X. Introducing the synthetic control method to the peacekeeping literature, I find X. Given the causal effect demonstrated by this study, the results from this analysis offer important insights for policymakers."
author:
  - "Brian Lookabaugh"
  - "University of North Texas"
format: 
  docx:
    toc: false
    reference-doc: (this determines font and formatting)
fontsize: 12pt
bibliography: (placeholder)
linkcolor: "#00853E"
citecolor: "#00853E"
crossref: 
  tbl-prefix: ""
  fig-prefix: ""
  eq-prefix: ""
---

```{r formatting setup, include=FALSE}
knitr::opts_chunk$set(
  cache = TRUE,
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  comment = ' ',
  fig.align = "center"
)

# Load Required Libraries
pacman::p_load(
  "tidyverse",
  install = FALSE
)

# Set Base Theme Settings for Plotting
theme_set(plot_theme(
  yaxis_size = 32,
  xaxis_size = 32,
  title_size = 40,
  strip_size = 26,
  subtitle_size = 30,
  x_axis_face = "bold",
  y_axis_face = "bold",
  strip_face = "bold",
  axis_text_size = 25,
  plot.background = element_rect(fill = "white", color = "white"),
  axis.text = element_text(size = 20),
  axis.line.x.bottom = element_line(colour = "black"),
  axis.line.y.left = element_line(colour = "black"),
  legend_text_size = 30
))
```

# Introduction

-   Introduce problem of causal inference in peacebuilding research
-   Introduce methods and case
-   Preview results

# The Literature on PKOs and Peacebuilding

Overwhelmingly, two decades of research have suggested a general conflict-reducing effect of third-party peacekeeping operations (PKOs) (Fortna and Howard 2008, Dorussen 2014, Walter et al. 2021). Indeed, this relationship has been established across a wide variety of operationalizations of peace, such as the rule of law (Blair 2019), economic recovery (Bove et al. 2021), inter-ethnic trust (Mironova and Whitt 2015), battle deaths (Vivalt 2015), the risk of conflict onset (Hegre et al. 2018), the risk of conflict recurrence (Fortna 2004, Quinn et al. 2007, Collier et al. 2008, Mason et al. 2011), civlian causalities (Hultman et al. 2013), and mass killings (Melander 2009). PKOs have been theorized to promote peace through their capacities to stop ongoing violence, to prevent formerly warring parties from re-engaging in conflict, and to address structural causes of violence.

In this first aspect of peace promotion, PKOs are theorized to serve as a "buffer" between groups engaged in ongoing violence. If a physical buffer is placed between warring parties, the chances of accidental engagement between groups that might disrupt the conflict termination process decreases. For those groups that may not be committed to the conflict termination process, PKOs make the process of reneging on ceasefires much more costly as PKOs can monitor which actors are violating a ceasefire. In addition, the mere presence of a PKO serving as a buffer can eliminate tactical advantages a reneging party may have had as the element of a surprise is spoiled by PKOs who publicly report violations of ceasefires. Given that PKOs often serve as buffers, reneging parties run the risk of armed confrontation with peacekeeping forces, which itself contains international costs on reputation.

In the post-conflict environment, PKOs are thought to contribute to post-conflict peace by resolving "commitment problems". In short, the commitment problem is a dilemma scholars studying conflict have identified that makes conflict recurrence a rational path for formerly-warring actors (Fearon 1995, Hartzell et al. 2001, Powell 2006). When warring parties are ready to "come to the table" and negotiate, these parties are aware that, regardless of the settlement they reach, the other party has an incentive to renege on the settlement when it is beneficial for them to do so. Barring a third-party enforcement mechanism, formerly-warring parties may return to war either because the incentive to renege increases or, for preventative purposes, under the expectation that the other party is about to renege on the settlement. In this role, PKOs can serve as a clear third-party guarantor of a settlement to help resolve the commitment problem. Lastly, recent studies have demonstrated that PKOs can serve to resolve underlying structural forces that may promote the onset and recurrence of violence. Examples of this include studies demonstrating a positive effect of PKOs on local economic well-being (Bove et al. 2021), inter-ethnic relations (Mironova and Whitt 2015), and the promotion of representative political institutions (Joshi 2013).

However, many scholars have documented disturbing occurrences that are associated with the onset of PKOs. Indeed, a large (and growing) literature details the links between U.N. PKOs and transactional sex, sex tourism, and human trafficking (Jennings 2010, Smith and Smith 2010, Smith and de la Cuesta 2011, Beber et al. 2017, Bell et al. 2018). While sexual abuse and predation is not necessarily an indicator that a post-conflict environment will return to conflict, it is nonetheless an indicator that PKOs may contribute to post-conflict grievances. Other scholars have noted the presence of "peacekeeping economies" in which local economies experience growth *because of a PKO*, but this growth is sensitive the PKO withdrawals (Jennings and Boas 2015, Jennings 2018, Beber et al. 2019). Theoretical works such as Kuperman (2008) and Rauchhaus (2009) have considered the possibility of unintentional conflict-enhancing side effects produced by humanitarian intervention. According to Kuperman (2008), as humanitarian interventions increase globally, the incentives to rebel in at-risk countries increases. Prospective rebels understand that rebellion is often accompanied by retaliation by the state that often targets civilians. In this way, humanitarian interventions designed to protect civilians can be manipulated by prospective rebels as a tool to combat the state. This creates a moral hazard effect where humanitarian intervention allegedly encourages riskier behavior by dissidents in at-risk countries. Rauchhaus (2009) acknowledged that third party actors can identify when their services are being taken advantage of, however, they can still be limited in their capacity to reduce this unintentional conflict-increasing activity by a lack of ability or will to police and punish provocative behavior. In sum, while the empirical evidence suggests a large pacifying effect of PKOs on peace, scholars have identified many worrying aspects of PKOs for peace.

Of course, not all PKOs are the same and it may be the case that some of these negative aspects can be partially explained through other factors. For example, many scholars have argued that characteristics of PKOs themselves determine whether a PKO will be effective at promoting peace. Haas and Ansorg demonstrated that increased troop quality within PKOs is associated with a reduction in civilian victimization. Bove and Ruggeri (2016) detailed a relationship between increased U.N. PKO troop diversity and a reduction in civilian deaths. In a later study (Bove and Ruggeri 2018), the authors also found that a reduction in civilian and battle-related deaths is associated with decreased geographic and cultural distance between the PKO-targeted state and the composition of peacekeepers themselves. Hultman et al. (2014) showed that an increase in armed U.N. peacekeeping personnel correlated with a reduction in battlefield deaths and a later study found a similar pacifying effect for the risk of conflict recurrence (Hutlman et al. 2016). Kathman and Wood (2016) find similar support for the pacifying effect of the militarization of U.N. personnel in PKOs during the post-conflict period. In contrast, Phayal (2019) found that the military capacity of U.N. peacekeeping forces does not impact levels of civilian victimization. Di Salvatore (2019) demonstrated a crime-reducing effect associated with an increase in U.N. police personnel while an increase in U.N. military personnel is associated with an opposite effect. Studying violence more broadly, Bara (2020) arrived at a similar conclusion where increases in U.N. police personnel are correlated with a decrease in violence in general. Increases in U.N. military personnel were found, in contrast, to be associated with a decrease in civilian victimization when perpetrated by formerly warring parties only.

While the study of U.N. PKO composition is perhaps the most popular in the literature seeking to understand the conditional effects of PKOs on peace, other studies have examined how temporal dynamics impact the pacifying effect of PKOs. Kathman and Wood (2011) demonstrated how impartial interventions (of which U.N. PKOs) are associated with an increase in violence in the short term but decreases in the long term. Gilligan and Sergenti (2007) found that PKOs appear to only be effective in the post-conflict period. Sambanis (2008) detailed how PKOs create peace in the short-term, but long-term peace requires PKOs to focus on building institutions that can sustain the peace following eventual withdrawals of the PKO itself. Other studies have considered war-time dynamics as factors conditioning the success of PKOs. Beardsley et al. (2019) found an interactive pacifying effect of peacekeeping and mediation on battle-related deaths. Fjelde et al. (2018) outlined how PKOs appear to be more effective at reducing civilian victimization when violence against civilians is committed by rebels. In contrast, PKOs seem to be less effective at reducing government-led civilian victimization. Phayal and Prins (2019) find a similar effect when analyzing PKO effectiveness at the sub-national level.

Undoubtedly, the literature analyzing the effects of peacekeeping on peace has led to many valuable contributions. However, a massive shortcoming in the contemporary literature is the inability of most pieces to speak in terms of "effects". In reality, the majority of the peacekeeping literature is limited to discussing findings within the context of correlations and associations. However, as a literature whose intent is to offer and evaluate policy-applicable conflict resolution strategies, the focus of these efforts *should* be placed on assessing causal effects. The following section of this paper argues that making causal inferences in the peacekeeping literature should be a priority of scholars engaged in this literature. In doing so, the following section also reviews and critiques current efforts within the literature at making causal inferences, while also offering potential paths forward to improve the achievement of causal inference in this literature.

# The State of Causal Research in the PKO Literature

While causal language in very much present in the PKO literature, causal methods are much less represented. Oftentimes, studies that do not employ a research design oriented towards making causal inferences will use causal terminology such "significantly reduce the risk of further conflict" (Collier et al. 2008, p. 473), "decreased the risk of another war" (Fortna 2004, p. 283), "sustain the peace" (Quinn et al. 2007, p. 183), and "reduces violence against noncombatants" (Hultman et al. 2013, p. 10) when referring to the alleged effects of PKOs on peace and violence. At first glance, this may seem to be simply a semantic quibble. However, we should be cautious of using causal language when using correlative methods. Kocher's (2014) critique of Hultman et al. (2013) demonstrates the need for such caution. While Hultman et al.'s (2013) work suggested a causal effect linking PKOs to the reduction of civilian casualties, Kocher's (2014) re-analysis found that such a causal interpretation was inaccurate given that one-sided violence had decreased on average prior to the onset of PKOs. Further, Kocher (2014) likewise demonstrated that much of the size of the effect between PKOs and violence against civilians was explained by the single case of Rwanda in 1994. Instances such as this, which rely on statistical modeling, should warrant caution of causal interpretations of regression coefficients, which require strong assumptions, such as strict exogeneity and a lack of omitted confounding variables, that are rarely met in the peacekeeping literature (Samii 2016, Keele et al. 2019).

That is not to say, however, that causal research is *impossible* in the peacekeeping literature. In select instances, researchers have manage to execute randomized controlled trials (RCTs) where access to the treatment is randomized so that no confounding can occur and causal estimates be be made (Mironova and Whitt 2015). However, these approaches are few and far between. Practically speaking, researchers do not typically have a say concerning the targets of peacebuilding programs, especially when that peacebuilding program is a PKO. Further, even if researchers had such capacity, it would be unethical to randomly assign potentially life-saving peacebuilding programs to some countries while others did not receive such treatment. In the absence of experimental data, many scholars in the field have adopted an instrumental variables approach to making causal inferences concerning the effect of PKOs (Sambanis 2008, Vivalt 2015, Ruggeri et al. 2017, Blair 2019, Bove et al. 2021). Recognizing that treatments can be explained by exogenous and endogenous factors, the instrumental variables approach seeks to remove aspects of the treatment that are endogenous and retain the exogenous aspects of the treatment. In particular, this method is appealing when there are theoretical reasons to believe that confounding variables are present that current data either does not or cannot account for. Instrumental variables adjusts for confounding factors by selecting only exogenous aspects of the treatment, thereby, removing any concerns of endogeneity produced by either known or unknown confounders. However, this approach has not been implemented without controversy. Gilligan and Sergenti (2007) criticized the use of instrumental variables, referring to causal estimates from such an approach as invalid. These authors argued that the literature has a good grasp on the confounders that complicate the relationship between PKOs and peace, rendering the concern of unknown confounders unimportant. Further, the authors were also skeptical that an instrument for this type of research *could* exist on the grounds that "Any factor that affects how long a war or its subsequent peace will last should also be taken into accout by the UN Security Council when it is deciding whether or not to allocate a mission" (Gilligan and Sergenti 2007, p. 91). Essentially, the authors argued that there are no exogenous aspects of the treatment (UN PKO) given that the authorization of PKOs are heavily influenced by endogenous factors related to conflict and peace duration.

Instead of instrumental variables, Gilligan and Sergenti (2007) suggested the adoption of matching as an approach to improve causal estimates in the peacekeeping literature. Indeed, matching is widely employed in the peacekeeping literature (Sambanis 2008, Kathman and Wood 2011, Hultman et al. 2013, Hultman et al. 2014, Ruggeri et al. 2017, Di Salvatore 2018, Fjelde et al. 2018, Haas and Ansorg 2018, Beber et al. 2019, Bara 2020), albeit, not always as a method to improve causal interpretation.

Much like the use of matching, fixed effects are often employed in the peacekeeping literature (Joshi 2013, Hultman et al. 2014, Kocher 2014, Bove and Ruggeri 2016, 2018, Di Salvatore 2018, Fjedle et al. 2018, Haas and Ansorg 2018, Beber et al. 2019, Blair 2019, Di Salvatore 2019, Phayal 2019, Phayal and Prins 2019, Bara 2020, Bove et al. 2021), oftentimes not explicitly for causal inference purposes. The implementation of fixed effects can be helpful for making causal inferences due to its capacity to control for all observed and unobserved *time-invariant* factors of a specific unit. By creating a dummy variable for each unit, researchers can remove confounding effects that are unit-specific. Confounding effects such as these are often hard, if not impossible, to identify, which lends credit to the implementation of fixed effects. However, two glaring issues with the implementation of fixed effects for making causal inferences in the PKO literature should be noted. First, the implementation of fixed effects for the study of PKOs *as an event* for the study of post-conflict peace is impossible given that the presence of a PKO in the prior conflict is a *time-invariant variable*. In other words, it is *fixed*, meaning that a scholar studying PKOs would be unable to determine the effect of PKOs independent of the other unit-specific fixed factors. This problem, in particular, can be avoided if one alters their research question and/or their measure of PKOs. For example, if one is studying the potentially pacifying effects of PKOs *during* conflict, then PKOs, as an effect, are not fixed because the data set covers the temporal range both pre- and post-PKO. Alternatively, if one chooses not to measure PKOs using a dummy, opting to include a fluid measure such as the number of personnel involved in the PKO instead, fixed effects can still be employed given that the PKO measure is no longer a time-invariant variable. Still, while fixed effects accounts for all time-invariant aspects of a unit, it does not eliminate the potential for a *time-variant* confounder to slip through the cracks and bias estimates. While time-specific factors can be accounted for with a two-way fixed effects model that controls for each individual time-unit, errors can still occur in obtaining causal estimates (Imai and Kim 2021).

A final, although less utilized, method for making causal inferences from observational peacekeeping data is the difference-in-differences (DiD) approach. To my knowledge, only one contribution to the literature has been made using this approach (Phayal 2019). Simply put, DiD estimates a causal effect by obtaining the difference in outcome for a treated and control group by factoring in differences between- and within-units pre- and post-treatment. In this way, DiD allows researchers to demonstrate the counter-factual outcome for treated units *had treatment never occurred*. To make accurate causal inferences using this approach, two assumptions should be met. First, the timing of treatment should be constant across all units that receive treatment. Within the context of PKOs, this will be violated for any study examining the causal effect of PKOs at the initiation of PKOs globally varies across time. Even at the sub-national level, this assumption could be violated given that PKOs may arrive to different regions at different times. Second, DiD relies on the parallel trends assumption, which assumes that the trend in the outcome of interest (violence against civilians for Phayal 2019) is largely the same for both treated and untreated units pre-treatment. In many contexts within the peacekeeping literature, this could easily be violated as sub-national units may vary wildly with respect to trends in outcomes. Within the context of violence against civilians, certain regions within a country may experience a trend dramatically different than others due to the concentration of the fighting, for example.

One particularly well-suited method for the study of the pacifying effects of PKOs is the synthetic control method (SCM). Much like difference-in-differences, the SCM attempts to answer the counter-factual question of "what would the outcome for a unit look like if a unit was never exposed to treatment?" Unlike DiD, the SCM is not burdened by the parallel trends assumption. While it does carry its own set of assumptions, I argue that the method is highly applicable to the peacekeeping literature. Further, its intuitive logic is particularly appealing for communicating causal effects. Below, I outline the synthetic control method, discussing its virtues, its limitations, and its functionality for making causal inferences.

# The Synthetic Control Method

-   Introduce the SCM in the literature and what it does and why it is good for PKO literature
-   Statistical inference with the SCM
-   Robustness checks with the SCM
-   Limitations of the SCM (see Abadie et al. 2021)

# Case Selection and Background

# Results

-   Synthetic Weights
-   Synthetic Compared to the Real
-   The Causal Effect of the PKO in X Country
-   Low-Level Death Gap Between Real and Synthetic Graph
-   Robustness Check 1: Leave-One-Out Estimation
-   Robustness Check 2: Alternative Predictors
-   Inference 1: Artificial Timing of Event (in-time placebo)
-   Inference 2: Treatment Applied to Non-Treated Units (in-space placebo) - With and Without Outliers
-   Post/Pre- MSPE Graph

# Conclusion

-   Summary of the state of causal research
-   Summary of results
-   Limits of this study
-   What Future Research Should Be
-   Policy Applicability
